# Site settings
title: Trey Mack
email: treymacksc@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  I am a full stack web developer specializing in reactive
  web applications and integration. Feel free to contact me on Twitter
  or via email.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.treymack.com" # the base hostname & protocol for your site
twitter_username: trey_mack
github_username:  treymack
permalink: /blog/:title
future: false
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
